import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MenuSidebar from "@/components/sidebar-menu/MenuSidebar";
import Seetings from "@/components/Seetings";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <div className="flex justify-between bg-bgColor px-10 pt-12 h-screen">
          <MenuSidebar />
          <div id="root" className="w-full px-5">
            {children}
          </div>
          <Seetings />
        </div>
      </body>
    </html>
  );
}
